version: "3.7"

services:
  nodejs:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./blog
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles/
      - media_volume:/home/app/web/mediafiles/
    depends_on:
      - db
      - nodejs
    expose:
      - 8000
    env_file:
      - ./.env.dev
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "3333:80"
    volumes:
      - static_volume:/home/app/web/staticfiles/
      - media_volume:/home/app/web/mediafiles/

volumes:
  postgres_data:
  static_volume:
  media_volume: