version: "3.7"


services:
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./blog
      dockerfile: Dockerfile
#    volumes:
#      - ./blog/:/usr/src/blog
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      - "1337:80"
    volumes:
#      - ./blog/static/:/static
      - ./blog/static/:/usr/src/blog/static

volumes:
  postgres_data:
  static: