version: "3.7"

services:
  nodejs:
    build:
      context: ./docker/nodejs
      dockerfile: Dockerfile
      args:
        STATIC: $STATIC
    volumes:
      - static:$STATIC
  db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build:
      context: ./blog
      dockerfile: Dockerfile.prod
      args:
        HOME: $HOME
        APP_HOME: $APP_HOME
        STATIC_FILES: $STATIC_FILES
        MEDIA_FILES: $MEDIA_FILES
    volumes:
      - static:$STATIC
      - static_volume:$STATIC_FILES
      - media_volume:$MEDIA_FILES
      - tmp:$TMP
    depends_on:
      - db
      - nodejs
    expose:
      - 8000
    env_file:
      - ./.env.prod
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
    ports:
      - "3333:80"
    volumes:
      - static_volume:$STATIC_FILES
      - media_volume:$MEDIA_FILES

volumes:
  postgres_data:
  static:
  static_volume:
  media_volume:
  tmp:
