version: "3.7"


services:
  blog_db:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=qwertytrewq
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  blog_web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/blog
    depends_on:
      - blog_db
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - blog_web
      - blog_db
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
#      - ./static/:/usr/src/blog/static
